/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UsersImport } from './routes/users'
import { Route as SupportImport } from './routes/support'
import { Route as SettingsImport } from './routes/settings'
import { Route as ServicesImport } from './routes/services'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as AnnouncementsImport } from './routes/announcements'
import { Route as AiTokensImport } from './routes/ai-tokens'
import { Route as IndexImport } from './routes/index'
import { Route as AdminIndexImport } from './routes/admin/index'
import { Route as AdminUsersImport } from './routes/admin/users'
import { Route as AdminSupportImport } from './routes/admin/support'
import { Route as AdminSettingsImport } from './routes/admin/settings'
import { Route as AdminServicesImport } from './routes/admin/services'
import { Route as AdminAnnouncementsImport } from './routes/admin/announcements'

// Create/Update Routes

const UsersRoute = UsersImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRoute,
} as any)

const SupportRoute = SupportImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRoute,
} as any)

const SettingsRoute = SettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const ServicesRoute = ServicesImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const AnnouncementsRoute = AnnouncementsImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRoute,
} as any)

const AiTokensRoute = AiTokensImport.update({
  id: '/ai-tokens',
  path: '/ai-tokens',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRoute,
} as any)

const AdminUsersRoute = AdminUsersImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRoute,
} as any)

const AdminSupportRoute = AdminSupportImport.update({
  id: '/admin/support',
  path: '/admin/support',
  getParentRoute: () => rootRoute,
} as any)

const AdminSettingsRoute = AdminSettingsImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRoute,
} as any)

const AdminServicesRoute = AdminServicesImport.update({
  id: '/admin/services',
  path: '/admin/services',
  getParentRoute: () => rootRoute,
} as any)

const AdminAnnouncementsRoute = AdminAnnouncementsImport.update({
  id: '/admin/announcements',
  path: '/admin/announcements',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/ai-tokens': {
      id: '/ai-tokens'
      path: '/ai-tokens'
      fullPath: '/ai-tokens'
      preLoaderRoute: typeof AiTokensImport
      parentRoute: typeof rootRoute
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportImport
      parentRoute: typeof rootRoute
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersImport
      parentRoute: typeof rootRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/admin/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsImport
      parentRoute: typeof rootRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/admin/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesImport
      parentRoute: typeof rootRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsImport
      parentRoute: typeof rootRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/admin/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportImport
      parentRoute: typeof rootRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersImport
      parentRoute: typeof rootRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-tokens': typeof AiTokensRoute
  '/announcements': typeof AnnouncementsRoute
  '/dashboard': typeof DashboardRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/users': typeof UsersRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-tokens': typeof AiTokensRoute
  '/announcements': typeof AnnouncementsRoute
  '/dashboard': typeof DashboardRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/users': typeof UsersRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/ai-tokens': typeof AiTokensRoute
  '/announcements': typeof AnnouncementsRoute
  '/dashboard': typeof DashboardRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/users': typeof UsersRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-tokens'
    | '/announcements'
    | '/dashboard'
    | '/services'
    | '/settings'
    | '/support'
    | '/users'
    | '/admin/announcements'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/users'
    | '/admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-tokens'
    | '/announcements'
    | '/dashboard'
    | '/services'
    | '/settings'
    | '/support'
    | '/users'
    | '/admin/announcements'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/ai-tokens'
    | '/announcements'
    | '/dashboard'
    | '/services'
    | '/settings'
    | '/support'
    | '/users'
    | '/admin/announcements'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/users'
    | '/admin/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiTokensRoute: typeof AiTokensRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  DashboardRoute: typeof DashboardRoute
  ServicesRoute: typeof ServicesRoute
  SettingsRoute: typeof SettingsRoute
  SupportRoute: typeof SupportRoute
  UsersRoute: typeof UsersRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiTokensRoute: AiTokensRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  DashboardRoute: DashboardRoute,
  ServicesRoute: ServicesRoute,
  SettingsRoute: SettingsRoute,
  SupportRoute: SupportRoute,
  UsersRoute: UsersRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/ai-tokens",
        "/announcements",
        "/dashboard",
        "/services",
        "/settings",
        "/support",
        "/users",
        "/admin/announcements",
        "/admin/services",
        "/admin/settings",
        "/admin/support",
        "/admin/users",
        "/admin/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/ai-tokens": {
      "filePath": "ai-tokens.tsx"
    },
    "/announcements": {
      "filePath": "announcements.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx"
    },
    "/services": {
      "filePath": "services.tsx"
    },
    "/settings": {
      "filePath": "settings.tsx"
    },
    "/support": {
      "filePath": "support.tsx"
    },
    "/users": {
      "filePath": "users.tsx"
    },
    "/admin/announcements": {
      "filePath": "admin/announcements.tsx"
    },
    "/admin/services": {
      "filePath": "admin/services.tsx"
    },
    "/admin/settings": {
      "filePath": "admin/settings.tsx"
    },
    "/admin/support": {
      "filePath": "admin/support.tsx"
    },
    "/admin/users": {
      "filePath": "admin/users.tsx"
    },
    "/admin/": {
      "filePath": "admin/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
