/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UsersImport } from './routes/users'
import { Route as SupportImport } from './routes/support'
import { Route as SettingsImport } from './routes/settings'
import { Route as ServicesImport } from './routes/services'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as AnnouncementsImport } from './routes/announcements'
import { Route as AiTokensImport } from './routes/ai-tokens'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const UsersRoute = UsersImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRoute,
} as any)

const SupportRoute = SupportImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRoute,
} as any)

const SettingsRoute = SettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const ServicesRoute = ServicesImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const AnnouncementsRoute = AnnouncementsImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRoute,
} as any)

const AiTokensRoute = AiTokensImport.update({
  id: '/ai-tokens',
  path: '/ai-tokens',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/ai-tokens': {
      id: '/ai-tokens'
      path: '/ai-tokens'
      fullPath: '/ai-tokens'
      preLoaderRoute: typeof AiTokensImport
      parentRoute: typeof rootRoute
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportImport
      parentRoute: typeof rootRoute
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-tokens': typeof AiTokensRoute
  '/announcements': typeof AnnouncementsRoute
  '/dashboard': typeof DashboardRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/users': typeof UsersRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-tokens': typeof AiTokensRoute
  '/announcements': typeof AnnouncementsRoute
  '/dashboard': typeof DashboardRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/users': typeof UsersRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/ai-tokens': typeof AiTokensRoute
  '/announcements': typeof AnnouncementsRoute
  '/dashboard': typeof DashboardRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/users': typeof UsersRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-tokens'
    | '/announcements'
    | '/dashboard'
    | '/services'
    | '/settings'
    | '/support'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-tokens'
    | '/announcements'
    | '/dashboard'
    | '/services'
    | '/settings'
    | '/support'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/ai-tokens'
    | '/announcements'
    | '/dashboard'
    | '/services'
    | '/settings'
    | '/support'
    | '/users'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiTokensRoute: typeof AiTokensRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  DashboardRoute: typeof DashboardRoute
  ServicesRoute: typeof ServicesRoute
  SettingsRoute: typeof SettingsRoute
  SupportRoute: typeof SupportRoute
  UsersRoute: typeof UsersRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiTokensRoute: AiTokensRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  DashboardRoute: DashboardRoute,
  ServicesRoute: ServicesRoute,
  SettingsRoute: SettingsRoute,
  SupportRoute: SupportRoute,
  UsersRoute: UsersRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/ai-tokens",
        "/announcements",
        "/dashboard",
        "/services",
        "/settings",
        "/support",
        "/users"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/ai-tokens": {
      "filePath": "ai-tokens.tsx"
    },
    "/announcements": {
      "filePath": "announcements.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx"
    },
    "/services": {
      "filePath": "services.tsx"
    },
    "/settings": {
      "filePath": "settings.tsx"
    },
    "/support": {
      "filePath": "support.tsx"
    },
    "/users": {
      "filePath": "users.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
